### PR TITLE
Replace Cobertura with JaCoCo.

### PR DESCRIPTION
**Pull request by alex-kar**
Fixes [#544](https://github.com/eeverman/andhow/issues/544)

* Replace Cobertura with JaCoCo in pom.xml.
* Ignore coverage report on build.
* Update travis.yml with command to generate coverage report.

### All Submissions:

Have you checked that...
* [+] Your pull request is to the *_main_* branch
* [+] Your code is up to date with the latest code from the *_main_*
* [+] You followed the guidelines in our [Developer Guide](https://sites.google.com/view/andhow/developer)?
* [+] Your code does not decrease test coverage (maybe it improves coverage!!)
* [+] If this is related to an issue, please include a link to the issue with the 'Fixes #XXX' syntax.

### CODE REVIEW

**Comment by eeverman** [comment]
Thank you @alex-kar.
Can you put a small change in your pull request to see if the Travis-CI will run?  It didn't run for your initial commit (there should be a code coverage report in the PR generated by JaCoCo if everything has worked correctly).
I made a change in the Travis integration, so a small change to your PR should now cause it to run, I think.

**Comment by eeverman** [comment]
I think the configuration in the pom file is not quite working correctly.  I checked out the code locally and ran the command:
`mvn clean test -Djacoco.skip=false`
It did generate some files, but the results were all empty.  For example the 'andhow-junit5-extensions' module should be very near 100% coverage, but shows no coverage.

**Comment by alex-kar** [comment]
@eeverman I pushed some changes to trigger Travis CI and I can see some generated report from Codecov now.
Also I tried to run `mvn clean test -Djacoco.skip=false` and after all tests passed it does generate report for me.
If I open index.html  under `andhow-junit5-extensions` it shows me 100% coverage.
In parent project it generated empty result.
Maven version 3.6.2.

**Comment by eeverman** [comment]
Thank you @alex-kar !  I didn't realize that the jacoco.exec file contained the actual coverage data.  It does look like its all working now.

I appreciate your help, especially with your knowledge of Maven!

**Review by eeverman — APPROVED** [review]
Nice work!

**Pull request merged**
