### PR TITLE
Add missing @Deprecated annotations

### LINKED ISSUE #596: Check for all cases where deprecation is in a comment but not in code
Another thing that could be done with this ticket:
All `@Deprecated` annotations should be marked as `forRemoval = true`.  The intention is to remove all the deprecations in the next release.  This applies to all deprecations, not just those missed up to this point.

### PR DESCRIPTION
**Pull request by alex-kar**
Fixes #596 

### All Submissions:

* Add missing `@Deprecated` annotations
* Mark all `@Deprecated` annotations for removal

Have you checked that...
* [x] Your pull request is to the *_main_* branch
* [x] Your code is up to date with the latest code from the *_main_*
* [x] You followed the guidelines in our [Developer Guide](https://sites.google.com/view/andhow/developer)?
* [x] Your code does not decrease test coverage (maybe it improves coverage!!)
* [x] If this is related to an issue, please include a link to the issue with the 'Fixes #XXX' syntax.

### CODE REVIEW

**Comment by alex-kar** [comment]
@eeverman Build failed, `Deprecated#forRemoval` method has been added in java 9.

**Review by eeverman — APPROVED** [review]
Looks good - Thanks!
(I see now its a draft - It looks like you are on the right track :-)

**Comment by alex-kar** [comment]
@eeverman Probably you missed my message above. It can't be compiled with java 8. What's the expected fix? Revert changes for `forRemoval = true`?

**Comment by eeverman** [comment]
@alex-kar Sorry, yes, I did miss your note.
Drat!  Only added in JDK 9 - I guess we cannot use it.  Sorry for the noise - I guess we just take out the 'forRemoval'.

**Comment by alex-kar** [comment]
@eeverman Thanks, took out `forRemoval`.

**Pull request merged**
