### PR TITLE
Merging master into 0.5.0

### PR DESCRIPTION
**Pull request by code4t2**
Pulled code from _master_ onto _0.5.0_

**Successfully merged with no conflicts.**

Seems like an interesting project. Also, somewhere along the way, an extra blank line has been added to all your files. (present in current (0966301ae38fea8ee55eb590246dc799a005dbcc) _master_, not seen in _0.5.0_)

Fixes: #445

### CODE REVIEW

**Comment by eeverman** [comment]
Thank you for looking at this. This pull request should be against the 0.5.0 branch, not master @code4t2

**Comment by code4t2** [comment]
Woah. Didn't notice it. Edited the PR to base it on 0.5.0. Sorry, @eeverman . First PR jitters, I guess 😊 Thanks very much for the opportunity.

**Comment by eeverman** [comment]
Thanks @code4t2!

If you would like to become a contributor on this project, let me know.

**Comment by code4t2** [comment]
Thank you very much, @eeverman 😄 

The project seems interesting and I'd love to help out as much as I can. I'd be honored.

**Pull request merged**
