### PR TITLE
Designed a logo

### PR DESCRIPTION
**Pull request by Gayathrir1666**

### CODE REVIEW

**Comment by eeverman** [comment]
Great logo submission @Gayathrir1666!

I cannot merge this one into the project, however, because:
* The merge request is going into the wrong branch
* The logo is not in a folder/directory

Can you please review the instructions at the bottom of this page and modify or resubmit your logo?
https://github.com/eeverman/andhow/tree/logo_submission

I like your logo - I don't want to lose it!

**Comment by harsh98trivedi** [comment]
@eeverman I've made another PR, have a look at that.

**Comment by Gayathrir1666** [comment]
@eeverman I will do it as per the requirement.

**Comment by eeverman** [comment]
You have submitted a new pull request, so I am closing this one.

**Pull request closed without merging**
